#!/usr/bin/env bash
# Publish the dashboard: uploads the sensor config, writes app-config.js from the
# stack outputs and syncs web/ to the web bucket.
#   tools/deploy_web.sh [stack-name] [gateway-config.json] [overrides.json]
# Defaults: sam-app, Akvo_Green's config_data/config.json, config/dashboard_overrides.json
# Refuses to publish when the gateway config's MQTT topics differ from the stack's.
set -euo pipefail
STACK="${1:-sam-app}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_ARGS=()
[ -n "${2:-}" ] && SRC_ARGS+=(--source "$2")
[ -n "${3:-}" ] && SRC_ARGS+=(--overrides "$3")

out() {
  aws cloudformation describe-stacks --stack-name "$STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}
param() {
  aws cloudformation describe-stacks --stack-name "$STACK" \
    --query "Stacks[0].Parameters[?ParameterKey=='$1'].ParameterValue" --output text
}

API_URL="$(out ApiUrl)"
API_KEY="$(aws apigateway get-api-key --api-key "$(out ApiKeyId)" --include-value --query value --output text)"
DATA_BUCKET="$(out DataBucketName)"
WEB_BUCKET="$(out WebBucketName)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Build locally first so the topics can be checked before anything is uploaded.
python3 "$ROOT/tools/sync_config.py" "${SRC_ARGS[@]}" --out "$TMP/config.json"
read -r CFG_DATA CFG_SYSTEM < <(python3 -c 'import json,sys; t=json.load(open(sys.argv[1]))["topics"]; print(t["data"], t["system"])' "$TMP/config.json")
STACK_DATA="$(param DataTopic)"
STACK_SYSTEM="$(param SystemTopic)"
if [ "$CFG_DATA" != "$STACK_DATA" ] || [ "$CFG_SYSTEM" != "$STACK_SYSTEM" ]; then
  echo "error: gateway config publishes to $CFG_DATA / $CFG_SYSTEM but stack $STACK listens on $STACK_DATA / $STACK_SYSTEM" >&2
  echo "       wrong config.json for this site? Nothing was uploaded." >&2
  exit 1
fi
python3 "$ROOT/tools/sync_config.py" "${SRC_ARGS[@]}" --bucket "$DATA_BUCKET"

cat > "$TMP/app-config.js" <<JS
// Generated by tools/deploy_web.sh for stack $STACK.
window.VENKO = { apiBase: "$API_URL", apiKey: "$API_KEY" };
JS

aws s3 sync "$ROOT/web/" "s3://$WEB_BUCKET/" --delete --exclude "app-config.example.js" --exclude "app-config.js"
aws s3 cp "$TMP/app-config.js" "s3://$WEB_BUCKET/app-config.js"
echo "Dashboard: $(out DashboardUrl)"
