#!/usr/bin/env bash
# Publish the dashboard: writes web/app-config.js from the stack outputs,
# uploads the sensor config and syncs web/ to the web bucket.
#   tools/deploy_web.sh [stack-name]        (default: venko-demo)
set -euo pipefail
STACK="${1:-venko-demo}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

out() {
  aws cloudformation describe-stacks --stack-name "$STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

API_URL="$(out ApiUrl)"
API_KEY="$(aws apigateway get-api-key --api-key "$(out ApiKeyId)" --include-value --query value --output text)"
DATA_BUCKET="$(out DataBucketName)"
WEB_BUCKET="$(out WebBucketName)"

python3 "$ROOT/tools/sync_config.py" --bucket "$DATA_BUCKET"

cat > "$ROOT/web/app-config.js" <<JS
// Generated by tools/deploy_web.sh for stack $STACK - do not commit.
window.VENKO = { apiBase: "$API_URL", apiKey: "$API_KEY" };
JS

aws s3 sync "$ROOT/web/" "s3://$WEB_BUCKET/" --delete --exclude "app-config.example.js"
echo "Dashboard: $(out DashboardUrl)"
