// Generated by tools/deploy_web.sh for stack sam-app - do not commit.
window.VENKO = { apiBase: "https://myuusccns9.execute-api.us-east-1.amazonaws.com/prod", apiKey: "WOkK44hA2t7g2hBPADidV53SEFTTIk2mapmZNOZK" };
